### ISSUE TITLE
Charge with more than 500w

### ISSUE THREAD

**Issue by Leono-Meistro** [redpomodoro/fronius_modbus#2]
I can't get the program to charge the battery with more than 500w from grid.

**Comment by orgiz** [comment]
Hi,

I have the same problem.  I’m having trouble using the “Grid Charge Power” function – nothing happens when I change that parameter. It's always stuck 500W charging when "Charge from Grid" is active.

Primo GEN24 6.0
Firmware: 1.30.7-1

**Comment by redpomodoro** [comment]
Working on a new version that is more intuitive to use. Currently the order of changing settings need to be followed to work.

**Comment by redpomodoro** [comment]
Closing this issue as it should be resolved with the latest version.
